/* ===== 血統くん refined — WIN5 データ (2026/6/21) ===== */

window.KB_WIN5 = {
  date: "2026.6.21",
  dow: "日",
  method: "1000回モンテカルロ・シミュレーション",
  modelNote: "単勝オッズ(市場評価)を土台に、近4走フォーム・距離/馬場適性で補正。",
  summary:
    "②東京10R(レッドキングリー)・⑤府中牝馬S(ヴァルキリーバース)が1頭軸で絞れる一方、①姫路S・③UHB杯は3〜4頭流しが無難。④しらさぎSは良馬場想定で⑪エコロアルバが浮上、稍重〜重ならサイルーン台頭。",
  races: [
    {
      leg: 1,
      time: "14:50",
      venue: "阪神",
      track: "ダ",
      name: "姫路S",
      course: "ダート1800m",
      class: "OP",
      raceNo: "10R",
      tip: "上位4頭が連勝・連対中の充実勢で混戦。1番人気アカデミアが軸も、抜けてはいない。",
      confidence: "C", // S/A/B/C — 拮抗度
      top: [
        { num: 9, name: "アカデミア", prob: 27.2, odds: 4.1, mark: "◎" },
        { num: 15, name: "ロカヒ", prob: 20.4, odds: 5.4, mark: "○" },
        { num: 6, name: "ルクスフレンジー", prob: 16.6, odds: 5.6, mark: "▲" },
        { num: 14, name: "レヴァンテシチー", prob: 15.5, odds: 6.5, mark: "△" },
        { num: 3, name: "アークドール", prob: 7.4, odds: 14.4, mark: "★" },
      ],
      buy: "3〜4頭流し推奨。⑨⑮⑥⑭",
    },
    {
      leg: 2,
      time: "15:00",
      venue: "東京",
      track: "芝",
      name: "多摩川S",
      course: "芝1400m",
      class: "OP",
      raceNo: "10R",
      tip: "東京巧者レッドキングリーが頭ひとつ抜けた評価。2強ムード。",
      confidence: "A",
      top: [
        { num: 9, name: "レッドキングリー", prob: 46.5, odds: 3.9, mark: "◎" },
        { num: 10, name: "ラーンザロープス", prob: 21.5, odds: 4.5, mark: "○" },
        { num: 2, name: "モンドデラモーレ", prob: 7.1, odds: 9.0, mark: "▲" },
        { num: 6, name: "ダノンエンブレム", prob: 6.4, odds: 8.9, mark: "△" },
        { num: 12, name: "マテンロウブラボー", prob: 6.2, odds: 11.5, mark: "★" },
      ],
      buy: "1頭軸 or 2頭で絞れる。⑨を軸に⑩を厚く",
    },
    {
      leg: 3,
      time: "15:25",
      venue: "函館",
      track: "芝",
      name: "UHB杯",
      course: "芝1200m",
      class: "OP",
      raceNo: "11R",
      tip: "上位3頭が拮抗、最も荒れやすいレース。",
      confidence: "C",
      top: [
        { num: 6, name: "シカゴスティング", prob: 29.8, odds: 4.8, mark: "◎" },
        { num: 12, name: "ドゥアムール", prob: 24.6, odds: 5.9, mark: "○" },
        { num: 11, name: "ヴェサリウス", prob: 21.1, odds: 7.2, mark: "▲" },
        { num: 14, name: "アスティスプマンテ", prob: 6.0, odds: 13.6, mark: "△" },
        { num: 3, name: "エヴァンスウィート", prob: 5.6, odds: 5.6, mark: "★" },
      ],
      buy: "3〜4頭流し必須。⑥⑫⑪を等価値で",
    },
    {
      leg: 4,
      time: "15:30",
      venue: "阪神",
      track: "芝",
      name: "しらさぎS",
      course: "芝1600m",
      class: "G3",
      raceNo: "11R",
      raceId: "shirasagiS2026",
      tip: "良馬場想定だと適性評価で⑪エコロアルバが浮上、サイルーンは6番手に後退。稍重〜重なら逆転の可能性。",
      confidence: "B",
      top: [
        { num: 11, name: "エコロアルバ", prob: 24.1, odds: 3.7, mark: "◎" },
        { num: 5, name: "ファーヴェント", prob: 20.8, odds: 6.2, mark: "○" },
        { num: 14, name: "ミニトランザット", prob: 14.4, odds: 8.1, mark: "▲" },
        { num: 17, name: "スイープアワーズ", prob: 12.2, odds: 13.5, mark: "△" },
        { num: 12, name: "カズミクラーシュ", prob: 6.8, odds: 16.4, mark: "★" },
      ],
      buy: "3頭流し。⑪⑤⑭で。当日の馬場で⑧サイルーンの追加検討",
      crossRef: "AI血統診断（馬場の目）では⑫カズミクラーシュが本命。WIN5モデルとは別視点なのでマルチで",
    },
    {
      leg: 5,
      time: "15:45",
      venue: "東京",
      track: "芝",
      name: "府中牝馬S",
      course: "芝1800m",
      class: "G2",
      raceNo: "11R",
      raceId: "fuchuFillies2026",
      tip: "ヴァルキリーバースが断然。軸として最も信頼できる1頭。",
      confidence: "S",
      top: [
        { num: 6, name: "ヴァルキリーバース", prob: 44.1, odds: 2.9, mark: "◎" },
        { num: 5, name: "エストゥペンダ", prob: 15.1, odds: 7.8, mark: "○" },
        { num: 8, name: "ニシノティアモ", prob: 13.9, odds: 6.5, mark: "▲" },
        { num: 15, name: "ルージュソリテール", prob: 8.6, odds: 12.5, mark: "△" },
        { num: 12, name: "コガネノソラ", prob: 6.9, odds: 7.0, mark: "★" },
      ],
      buy: "1頭軸 ⑥ヴァルキリーバース",
      crossRef: "AI血統診断（馬場の目）では⑥は危険馬扱い。WIN5モデルでは断然。判断割れる注目馬",
    },
  ],
};
